{% set name = "metview-python" %}
{% set pypi_name = "metview" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 754ceceeb7999457f99495686129d885cfb6b62fc433d3a0f2aad879ceb2fece

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - pytest-runner
  run:
    - cffi
    - cfgrib
    - numpy
    - pandas
    - python >=3.6
    - PyYAML
    - requests
    - xarray

test:
  commands:
    - test -f $(python -c "import site; print(site.getsitepackages()[0])")/metview/__init__.py  # [not win]

about:
  home: https://github.com/ecmwf/metview-python
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
  summary: Python interface to process and plot meteorological data in GRIB, NetCDF, BUFR and more.

extra:
  recipe-maintainers:
    - iainrussell
    - sandorkertesz
