{% set name = "metview-python" %}
{% set pypi_name = "metview" %}
{% set version = "1.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 4748ced94c3d94b0bf24e8f63014eff390762a4461964392518b29844c534f95

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytest-runner
  run:
    - cffi
    - cfgrib
    - numpy
    - pandas
    - python >={{ python_min }}
    - PyYAML
    - requests
    - xarray

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $(python -c "import site; print(site.getsitepackages()[0])")/metview/__init__.py  # [not win]

about:
  home: https://github.com/ecmwf/metview-python
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
  summary: Python interface to process and plot meteorological data in GRIB, NetCDF, BUFR and more.

extra:
  recipe-maintainers:
    - iainrussell
    - sandorkertesz
